# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default
  #vmImage: windows-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ES-CE-CUS-EXT-jechase(badceb30-7a80-4167-a047-ce4cb51f5d82)'
    subscriptionId: 'badceb30-7a80-4167-a047-ce4cb51f5d82'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-cicd'
    location: 'North Central US'
    templateLocation: 'Linked artifact'
    csmFile: '101-vm-simple-linux/azuredeploy.json'
    csmParametersFile: '101-vm-simple-linux/azuredeploy.parameters.json'
    overrideParameters: '-adminUsername "azadmin" -adminPassword "&nterPlease!21"'
    deploymentMode: 'Validation'